"""empty message

Revision ID: 85305457bfb4
Revises: 0a21c3da577f
Create Date: 2023-10-26 11:55:37.389738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85305457bfb4'
down_revision = '0a21c3da577f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc', schema=None) as batch_op:
        batch_op.alter_column('deployment_successful',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc', schema=None) as batch_op:
        batch_op.alter_column('deployment_successful',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
