"""Add code_change_volume column

Revision ID: a5d65c70c185
Revises: 3011b84cd898
Create Date: 2023-10-17 08:58:34.338903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d65c70c185'
down_revision = '3011b84cd898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cd_metrik', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code_change_volume', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cd_metrik', schema=None) as batch_op:
        batch_op.drop_column('code_change_volume')

    # ### end Alembic commands ###
