"""empty message

Revision ID: d31aa6b7a6aa
Revises: 49810ee574e0
Create Date: 2023-10-19 12:53:09.718638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31aa6b7a6aa'
down_revision = '49810ee574e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('projekt_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_incident_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident', schema=None) as batch_op:
        batch_op.drop_constraint('fk_incident_user_id', type_='foreignkey')
        batch_op.alter_column('projekt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
