"""empty message

Revision ID: d60e16d204f8
Revises: f773ac403d7e
Create Date: 2023-10-20 11:16:05.682223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60e16d204f8'
down_revision = 'f773ac403d7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_datetime', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('deployment_datetime', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ltc', schema=None) as batch_op:
        batch_op.drop_column('deployment_datetime')
        batch_op.drop_column('commit_datetime')

    # ### end Alembic commands ###
