"""empty message

Revision ID: e3c1ad9ad932
Revises: 85305457bfb4
Create Date: 2023-12-15 12:23:46.982707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c1ad9ad932'
down_revision = '85305457bfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cd_metrik', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commit_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cd_metrik', schema=None) as batch_op:
        batch_op.drop_column('commit_datetime')

    # ### end Alembic commands ###
